// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YOGBIS.Data.DataContext;

namespace YOGBIS.Data.Migrations
{
    [DbContext(typeof(YOGBISContext))]
    [Migration("20220118141001_tabloyukleme")]
    partial class tabloyukleme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(127)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(127)")
                        .HasMaxLength(127);

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.EntityFrameworkCore.AutoHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Changed")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("AutoHistory");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.AdayDDK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdayId")
                        .HasColumnType("int");

                    b.Property<int>("AdayTC")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AdayId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("AdayDDKs");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.AdayGorevKaydi", b =>
                {
                    b.Property<int>("AdayGorevKaydiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BransId")
                        .HasColumnType("int");

                    b.Property<int>("DereceId")
                        .HasColumnType("int");

                    b.Property<int?>("EyaletId")
                        .HasColumnType("int");

                    b.Property<string>("GorevAciklama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GorevBasTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("GorevBitisTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("GorevDurumu")
                        .HasColumnType("int");

                    b.Property<string>("GorevOnaySayi")
                        .HasColumnType("text");

                    b.Property<string>("Gorevi")
                        .HasColumnType("text");

                    b.Property<DateTime>("GorevlOnayTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("GorevlendirilmeTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("GorevliTC")
                        .HasColumnType("int");

                    b.Property<string>("KararPdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("OkulId")
                        .HasColumnType("int");

                    b.Property<int?>("OkullarOkulId")
                        .HasColumnType("int");

                    b.Property<int?>("SehirId")
                        .HasColumnType("int");

                    b.Property<int?>("SehirlerSehirId")
                        .HasColumnType("int");

                    b.Property<int?>("TemsilcilikId")
                        .HasColumnType("int");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.Property<int?>("UniId")
                        .HasColumnType("int");

                    b.Property<int?>("UniversitelerUniId")
                        .HasColumnType("int");

                    b.HasKey("AdayGorevKaydiId");

                    b.HasIndex("BransId");

                    b.HasIndex("DereceId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("OkullarOkulId");

                    b.HasIndex("SehirlerSehirId");

                    b.HasIndex("UlkeId");

                    b.HasIndex("UniversitelerUniId");

                    b.ToTable("AdayGorevKaydis");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.AdayNot", b =>
                {
                    b.Property<int>("AdayNotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdayId")
                        .HasColumnType("int");

                    b.Property<int>("AdayTC")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KomisyonId")
                        .HasColumnType("int");

                    b.Property<int>("KomisyonUyeSiraId")
                        .HasColumnType("int");

                    b.Property<int>("MulakatId")
                        .HasColumnType("int");

                    b.Property<int>("Not")
                        .HasColumnType("int");

                    b.Property<int>("NotKategoriId")
                        .HasColumnType("int");

                    b.HasKey("AdayNotId");

                    b.HasIndex("AdayId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("AdayNots");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Adaylar", b =>
                {
                    b.Property<int>("AdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdayAd")
                        .HasColumnType("text");

                    b.Property<string>("AdayAnaAd")
                        .HasColumnType("text");

                    b.Property<string>("AdayBabaAd")
                        .HasColumnType("text");

                    b.Property<string>("AdayFotoURL")
                        .HasColumnType("text");

                    b.Property<string>("AdaySoyad")
                        .HasColumnType("text");

                    b.Property<int>("AdayTC")
                        .HasColumnType("int");

                    b.Property<string>("AdresIl")
                        .HasColumnType("text");

                    b.Property<string>("AdresIlce")
                        .HasColumnType("text");

                    b.Property<string>("AritmetikOrtalama")
                        .HasColumnType("text");

                    b.Property<string>("Askerlik")
                        .HasColumnType("text");

                    b.Property<string>("BasvuranIP")
                        .HasColumnType("text");

                    b.Property<string>("BasvuruTarihi")
                        .HasColumnType("text");

                    b.Property<string>("Brans")
                        .HasColumnType("text");

                    b.Property<string>("CepTelNo")
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("text");

                    b.Property<string>("DahaOnceYYGorev")
                        .HasColumnType("text");

                    b.Property<string>("Derece")
                        .HasColumnType("text");

                    b.Property<int>("DereceId")
                        .HasColumnType("int");

                    b.Property<string>("DisiplinCeza")
                        .HasColumnType("text");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("text");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("text");

                    b.Property<string>("EPosta")
                        .HasColumnType("text");

                    b.Property<string>("Enaz5Yil")
                        .HasColumnType("text");

                    b.Property<int?>("GorevDurumu")
                        .HasColumnType("int");

                    b.Property<string>("HizmetAy")
                        .HasColumnType("text");

                    b.Property<string>("HizmetGun")
                        .HasColumnType("text");

                    b.Property<string>("HizmetYil")
                        .HasColumnType("text");

                    b.Property<string>("IlMemGorus")
                        .HasColumnType("text");

                    b.Property<string>("IlTercihi")
                        .HasColumnType("text");

                    b.Property<string>("Kademe")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumKod")
                        .HasColumnType("text");

                    b.Property<string>("MYSPuan")
                        .HasColumnType("text");

                    b.Property<string>("MYSSTAciklama")
                        .HasColumnType("text");

                    b.Property<string>("MYSSinavTarihi")
                        .HasColumnType("text");

                    b.Property<string>("MYSSinavTedbiri")
                        .HasColumnType("text");

                    b.Property<string>("MYSSonuc")
                        .HasColumnType("text");

                    b.Property<string>("MezunOkulAdi")
                        .HasColumnType("text");

                    b.Property<string>("MezunOkulKodu")
                        .HasColumnType("text");

                    b.Property<string>("MulakatDurum")
                        .HasColumnType("text");

                    b.Property<string>("MulakatDurumAciklama")
                        .HasColumnType("text");

                    b.Property<int>("MulakatId")
                        .HasColumnType("int");

                    b.Property<string>("Ogrenim")
                        .HasColumnType("text");

                    b.Property<string>("OnayAciklama")
                        .HasColumnType("text");

                    b.Property<string>("OnayDurumu")
                        .HasColumnType("text");

                    b.Property<string>("OnayTarihi")
                        .HasColumnType("text");

                    b.Property<string>("Onaylayan")
                        .HasColumnType("text");

                    b.Property<string>("SonucDurumu")
                        .HasColumnType("text");

                    b.Property<string>("TYSPuan")
                        .HasColumnType("text");

                    b.Property<string>("TYSSaat")
                        .HasColumnType("text");

                    b.Property<string>("TYSTarih")
                        .HasColumnType("text");

                    b.Property<string>("UlkeTercihi")
                        .HasColumnType("text");

                    b.Property<string>("YIciGorevBasTar")
                        .HasColumnType("text");

                    b.Property<string>("YYSonrasi2Yil")
                        .HasColumnType("text");

                    b.Property<string>("YabanciDilAdi")
                        .HasColumnType("text");

                    b.Property<string>("YabanciDilSeviye")
                        .HasColumnType("text");

                    b.Property<string>("YabanciDilTarihi")
                        .HasColumnType("text");

                    b.Property<string>("YabanciDilTuru")
                        .HasColumnType("text");

                    b.HasKey("AdayId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("MulakatId");

                    b.ToTable("Adaylars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Branslar", b =>
                {
                    b.Property<int>("BransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BransAdi")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("BransId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("Branslars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Duyurular", b =>
                {
                    b.Property<int>("DuyurularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DuyuruBaslık")
                        .HasColumnType("text");

                    b.Property<string>("DuyuruDetay")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("DuyurularId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("Duyurulars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.EPostaAdresleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EpostaAdresi")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("KaydedenId");

                    b.ToTable("EPostaAdresleris");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Etkinlikler", b =>
                {
                    b.Property<int>("EtkinlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BasTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("BitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("DuzenleyenAdiSoyadi")
                        .HasColumnType("text");

                    b.Property<string>("EtkinlikAdi")
                        .HasColumnType("text");

                    b.Property<string>("EtkinlikBilgi")
                        .HasColumnType("text");

                    b.Property<string>("EtkinlikDosyaUrl")
                        .HasColumnType("text");

                    b.Property<string>("EtkinlikKapakResimUrl")
                        .HasColumnType("text");

                    b.Property<int>("KatilimciSayisi")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("OkulId")
                        .HasColumnType("int");

                    b.HasKey("EtkinlikId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("OkulId");

                    b.ToTable("Etkinliklers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Eyaletler", b =>
                {
                    b.Property<int>("EyaletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EyaletAciklama")
                        .HasColumnType("text");

                    b.Property<string>("EyaletAdi")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.HasKey("EyaletId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("UlkeId");

                    b.ToTable("Eyaletlers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.FotoGaleri", b =>
                {
                    b.Property<int>("FotoGaleriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdayId")
                        .HasColumnType("int");

                    b.Property<int?>("AdaylarAdayId")
                        .HasColumnType("int");

                    b.Property<int?>("DuyurularId")
                        .HasColumnType("int");

                    b.Property<int?>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<int?>("EtkinliklerEtkinlikId")
                        .HasColumnType("int");

                    b.Property<string>("FotoAdi")
                        .HasColumnType("text");

                    b.Property<string>("FotoURL")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("OkulId")
                        .HasColumnType("int");

                    b.Property<int?>("OkullarOkulId")
                        .HasColumnType("int");

                    b.Property<int?>("SehirId")
                        .HasColumnType("int");

                    b.Property<int?>("SehirlerSehirId")
                        .HasColumnType("int");

                    b.Property<int?>("UlkeId")
                        .HasColumnType("int");

                    b.Property<int?>("UlkelerUlkeId")
                        .HasColumnType("int");

                    b.Property<int?>("UniId")
                        .HasColumnType("int");

                    b.Property<int?>("UniversitelerUniId")
                        .HasColumnType("int");

                    b.HasKey("FotoGaleriId");

                    b.HasIndex("AdaylarAdayId");

                    b.HasIndex("DuyurularId");

                    b.HasIndex("EtkinliklerEtkinlikId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("OkullarOkulId");

                    b.HasIndex("SehirlerSehirId");

                    b.HasIndex("UlkelerUlkeId");

                    b.HasIndex("UniversitelerUniId");

                    b.ToTable("FotoGaleris");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.GorevKararPdfGaleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdayGorevKaydiId")
                        .HasColumnType("int");

                    b.Property<string>("GorevKararPdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AdayGorevKaydiId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("GorevKararPdfGaleris");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.IkametAdresleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresTuru")
                        .HasColumnType("text");

                    b.Property<string>("IkametAdresi")
                        .HasColumnType("text");

                    b.Property<int>("IkametIlId")
                        .HasColumnType("int");

                    b.Property<int>("IkametIlceId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IkametIlceId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("IkametAdresleris");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Ilceler", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlceAdi")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("IlceId");

                    b.HasIndex("IlId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("Ilcelers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Iller", b =>
                {
                    b.Property<int>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IlAdi")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("PlakaKodu")
                        .HasColumnType("text");

                    b.HasKey("IlId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("Illers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.IllerMdEPosta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IlEPostaAdres")
                        .HasColumnType("text");

                    b.Property<string>("IlEpostaAdresAciklama")
                        .HasColumnType("text");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("IlId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("IllerMdEPostas");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Kitalar", b =>
                {
                    b.Property<int>("KitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KitaAciklama")
                        .HasColumnType("text");

                    b.Property<string>("KitaAdi")
                        .HasColumnType("text");

                    b.Property<int?>("UlkeGruplariUlkeGrupId")
                        .HasColumnType("int");

                    b.HasKey("KitaId");

                    b.HasIndex("UlkeGruplariUlkeGrupId");

                    b.ToTable("Kitalars");

                    b.HasData(
                        new
                        {
                            KitaId = 1,
                            KitaAciklama = "Afrika Kıtası",
                            KitaAdi = "Afrika"
                        },
                        new
                        {
                            KitaId = 2,
                            KitaAciklama = "Antartika Kıtası",
                            KitaAdi = "Antartika"
                        },
                        new
                        {
                            KitaId = 3,
                            KitaAciklama = "Asya Kıtası",
                            KitaAdi = "Asya"
                        },
                        new
                        {
                            KitaId = 4,
                            KitaAciklama = "Avrupa Kıtası",
                            KitaAdi = "Avrupa"
                        },
                        new
                        {
                            KitaId = 5,
                            KitaAciklama = "Avustralya Kıtası",
                            KitaAdi = "Avustralya"
                        },
                        new
                        {
                            KitaId = 6,
                            KitaAciklama = "Güney Amerika Kıtası",
                            KitaAdi = "Güney Amerika"
                        },
                        new
                        {
                            KitaId = 7,
                            KitaAciklama = "Kuzey Amerika Kıtası",
                            KitaAdi = "Kuzey Amerika"
                        });
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Komisyonlar", b =>
                {
                    b.Property<int>("KomisyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("KomisyoUyeStatu")
                        .HasColumnType("text");

                    b.Property<string>("KomisyoUyeTel")
                        .HasColumnType("text");

                    b.Property<string>("KomisyonAdi")
                        .HasColumnType("text");

                    b.Property<DateTime>("KomisyonGorevBaslamaTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("KomisyonGorevBitisTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KomisyonGorevi")
                        .HasColumnType("int");

                    b.Property<string>("KomisyonUyeAdiSoyadi")
                        .HasColumnType("text");

                    b.Property<string>("KomisyonUyeEPosta")
                        .HasColumnType("text");

                    b.Property<string>("KomisyonUyeGorevYeri")
                        .HasColumnType("text");

                    b.Property<int>("KomisyonUyeSiraId")
                        .HasColumnType("int");

                    b.Property<int>("MulakatId")
                        .HasColumnType("int");

                    b.HasKey("KomisyonId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("MulakatId");

                    b.ToTable("Komisyonlars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.MulakatSorulari", b =>
                {
                    b.Property<int>("MulakatSorulariId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cevap")
                        .HasColumnType("text");

                    b.Property<string>("DereceAdi")
                        .HasColumnType("text");

                    b.Property<int>("DereceId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("MulakatId")
                        .HasColumnType("int");

                    b.Property<string>("Soru")
                        .HasColumnType("text");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<string>("SoruKategoriAdi")
                        .HasColumnType("text");

                    b.Property<int>("SoruKategoriId")
                        .HasColumnType("int");

                    b.Property<int>("SoruSiraNo")
                        .HasColumnType("int");

                    b.Property<int?>("SorulanAdayTC")
                        .HasColumnType("int");

                    b.HasKey("MulakatSorulariId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("MulakatId");

                    b.ToTable("MulakatSorularis");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Mulakatlar", b =>
                {
                    b.Property<int>("MulakatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdaySayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("DereceId")
                        .HasColumnType("int");

                    b.Property<bool>("Durumu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("MulakatAciklama")
                        .HasColumnType("text");

                    b.Property<string>("MulakatAdi")
                        .HasColumnType("text");

                    b.Property<string>("OnaySayisi")
                        .HasColumnType("text");

                    b.Property<int?>("SorulanSoruSayisi")
                        .HasColumnType("int");

                    b.HasKey("MulakatId");

                    b.HasIndex("DereceId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("Mulakatlars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Notlar", b =>
                {
                    b.Property<int>("NotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BaTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("BiTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("NotAdi")
                        .HasColumnType("text");

                    b.Property<string>("NotDetay")
                        .HasColumnType("text");

                    b.Property<string>("NotRenk")
                        .HasColumnType("text");

                    b.HasKey("NotId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("Notlars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Ogrenciler", b =>
                {
                    b.Property<int>("OgrencilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Cinsiyet")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("OkulKayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.Property<string>("Uyruk")
                        .HasColumnType("text");

                    b.HasKey("OgrencilerId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("SinifId");

                    b.ToTable("Ogrencilers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.OkulBilgi", b =>
                {
                    b.Property<int>("OkulBilgiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("MdYrdAdiSoyadi")
                        .HasColumnType("text");

                    b.Property<string>("MdYrdDonusYil")
                        .HasColumnType("text");

                    b.Property<string>("MdYrdEPosta")
                        .HasColumnType("text");

                    b.Property<string>("MdYrdTelefon")
                        .HasColumnType("text");

                    b.Property<string>("MudurAdiSoyadi")
                        .HasColumnType("text");

                    b.Property<string>("MudurDonusYil")
                        .HasColumnType("text");

                    b.Property<string>("MudurEPosta")
                        .HasColumnType("text");

                    b.Property<string>("MudurTelefon")
                        .HasColumnType("text");

                    b.Property<string>("OkulAdres")
                        .HasColumnType("text");

                    b.Property<int>("OkulId")
                        .HasColumnType("int");

                    b.Property<string>("OkulTelefon")
                        .HasColumnType("text");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.HasKey("OkulBilgiId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OkulId");

                    b.ToTable("OkulBilgis");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Okullar", b =>
                {
                    b.Property<int>("OkulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("OkulAcilisTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("OkulAdi")
                        .HasColumnType("text");

                    b.Property<string>("OkulBilgi")
                        .HasColumnType("text");

                    b.Property<bool?>("OkulDurumu")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OkulKodu")
                        .HasColumnType("int");

                    b.Property<bool?>("OkulKutuphane")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("OkulLab")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OkulLogo")
                        .HasColumnType("text");

                    b.Property<string>("OkulMudurId")
                        .HasColumnType("text");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.HasKey("OkulId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("SehirId");

                    b.ToTable("Okullars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Personeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("PersonelAdiSoyadi")
                        .HasColumnType("text");

                    b.Property<string>("PersonelEPosta")
                        .HasColumnType("text");

                    b.Property<string>("PersonelGorevAlani")
                        .HasColumnType("text");

                    b.Property<string>("PersonelGrupAdi")
                        .HasColumnType("text");

                    b.Property<string>("PersonelTelefon")
                        .HasColumnType("text");

                    b.Property<string>("PersonelUnvan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KaydedenId");

                    b.ToTable("Personellers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SSS", b =>
                {
                    b.Property<int>("SSSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Soru")
                        .HasColumnType("text");

                    b.HasKey("SSSId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("SSSs");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SSSCevap", b =>
                {
                    b.Property<int>("SSSCevapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("SSSCevapDetay")
                        .HasColumnType("text");

                    b.Property<int>("SSSId")
                        .HasColumnType("int");

                    b.HasKey("SSSCevapId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("SSSId");

                    b.ToTable("SSSCevaps");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Sehirler", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Baskent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EyaletId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("SehirAciklama")
                        .HasColumnType("text");

                    b.Property<string>("SehirAdi")
                        .HasColumnType("text");

                    b.Property<int>("SehirVatandas")
                        .HasColumnType("int");

                    b.Property<string>("TemsilciId")
                        .HasColumnType("text");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.Property<int?>("UlkelerUlkeId")
                        .HasColumnType("int");

                    b.HasKey("SehirId");

                    b.HasIndex("EyaletId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("UlkelerUlkeId");

                    b.ToTable("Sehirlers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Siniflar", b =>
                {
                    b.Property<int>("SinifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("SinifAcilisTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("SinifAdi")
                        .HasColumnType("text");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("SinifId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("SubeId");

                    b.ToTable("Siniflars");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruBankasi", b =>
                {
                    b.Property<int>("SoruBankasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cevap")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Soru")
                        .HasColumnType("text");

                    b.Property<bool>("SoruDurumu")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SorulmaSayisi")
                        .HasColumnType("int");

                    b.HasKey("SoruBankasiId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("SoruBankasis");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruBankasiLog", b =>
                {
                    b.Property<int>("SoruBankasiLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cevap")
                        .HasColumnType("text");

                    b.Property<int>("DereceId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KayitTuru")
                        .HasColumnType("int");

                    b.Property<string>("Soru")
                        .HasColumnType("text");

                    b.Property<int>("SoruBankasiId")
                        .HasColumnType("int");

                    b.Property<bool>("SoruDurumu")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SoruKategoriId")
                        .HasColumnType("int");

                    b.Property<int>("SorulmaSayisi")
                        .HasColumnType("int");

                    b.HasKey("SoruBankasiLogId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("SoruBankasiId");

                    b.ToTable("SoruBankasiLogs");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruDerece", b =>
                {
                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<int>("DereceId")
                        .HasColumnType("int");

                    b.HasKey("SoruId", "DereceId");

                    b.HasIndex("DereceId");

                    b.ToTable("SoruDereces");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruDereceler", b =>
                {
                    b.Property<int>("DereceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DereceAdi")
                        .HasColumnType("text");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("DereceId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("SoruDerecelers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruKategori", b =>
                {
                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("SoruId", "KategoriId");

                    b.HasIndex("KategoriId");

                    b.ToTable("SoruKategoris");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruKategoriler", b =>
                {
                    b.Property<int>("SoruKategorilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DereceId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("SoruKategorilerAdi")
                        .HasColumnType("text");

                    b.Property<string>("SoruKategorilerKullanimi")
                        .HasColumnType("text");

                    b.Property<int>("SoruKategorilerPuan")
                        .HasColumnType("int");

                    b.HasKey("SoruKategorilerId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("SoruKategorilers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruOnay", b =>
                {
                    b.Property<int>("SoruOnayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("OnayAciklama")
                        .HasColumnType("text");

                    b.Property<int>("OnayDurumu")
                        .HasColumnType("int");

                    b.Property<string>("OnaylayanId")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("SoruBankasiId")
                        .HasColumnType("int");

                    b.HasKey("SoruOnayId");

                    b.HasIndex("OnaylayanId");

                    b.HasIndex("SoruBankasiId");

                    b.ToTable("SoruOnays");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Subeler", b =>
                {
                    b.Property<int>("SubeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("OkulAdi")
                        .HasColumnType("text");

                    b.Property<int>("OkulId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubeAcilisTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("SubeId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("OkulId");

                    b.ToTable("Subelers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Temsilcilikler", b =>
                {
                    b.Property<int>("TemsilcilikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.Property<string>("TemsilciId")
                        .HasColumnType("text");

                    b.Property<string>("TemsilcilikAdi")
                        .HasColumnType("text");

                    b.Property<string>("TemsilcilikEPosta")
                        .HasColumnType("text");

                    b.Property<string>("TemsilcilikTel")
                        .HasColumnType("text");

                    b.Property<string>("TemsilcilikWebAdres")
                        .HasColumnType("text");

                    b.HasKey("TemsilcilikId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("SehirId");

                    b.ToTable("Temsilciliklers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.UlkeGruplari", b =>
                {
                    b.Property<int>("UlkeGrupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KitaId")
                        .HasColumnType("int");

                    b.Property<string>("UlkeGrupAciklama")
                        .HasColumnType("text");

                    b.Property<string>("UlkeGrupAdi")
                        .HasColumnType("text");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.HasKey("UlkeGrupId");

                    b.HasIndex("KaydedenId");

                    b.ToTable("UlkeGruplaris");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Ulkeler", b =>
                {
                    b.Property<int>("UlkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KitaId")
                        .HasColumnType("int");

                    b.Property<string>("UlkeAciklama")
                        .HasColumnType("text");

                    b.Property<string>("UlkeAdi")
                        .HasColumnType("text");

                    b.Property<string>("UlkeBayrakURL")
                        .HasColumnType("text");

                    b.HasKey("UlkeId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("KitaId");

                    b.ToTable("Ulkelers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Universiteler", b =>
                {
                    b.Property<int>("UniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EyaletId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.Property<string>("UniAdi")
                        .HasColumnType("text");

                    b.Property<string>("UniBilgi")
                        .HasColumnType("text");

                    b.Property<string>("UniLogo")
                        .HasColumnType("text");

                    b.Property<string>("UniStatu")
                        .HasColumnType("text");

                    b.Property<bool>("YurtIciMi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UniId");

                    b.HasIndex("KaydedenId");

                    b.HasIndex("SehirId");

                    b.ToTable("Universitelers");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Kullanici", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KulaniciAdDegLimiti")
                        .HasColumnType("int");

                    b.Property<byte[]>("KullaniciResim")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("KullaniciResimYol")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<int?>("TcKimlikNo")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Kullanici");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.AdayDDK", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Adaylar", "Adaylar")
                        .WithMany("AdayDDKs")
                        .HasForeignKey("AdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("AdayDDKs")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.AdayGorevKaydi", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Branslar", "Branslar")
                        .WithMany()
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.SoruDereceler", "SoruDereceler")
                        .WithMany()
                        .HasForeignKey("DereceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("AdayGorevKaydis")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Okullar", null)
                        .WithMany("AdayGorevKaydis")
                        .HasForeignKey("OkullarOkulId");

                    b.HasOne("YOGBIS.Data.DbModels.Sehirler", null)
                        .WithMany("AdayGorevKaydis")
                        .HasForeignKey("SehirlerSehirId");

                    b.HasOne("YOGBIS.Data.DbModels.Ulkeler", "Ulkeler")
                        .WithMany()
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Universiteler", null)
                        .WithMany("AdayGorevKaydis")
                        .HasForeignKey("UniversitelerUniId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.AdayNot", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Adaylar", "Adaylar")
                        .WithMany("AdayNots")
                        .HasForeignKey("AdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("AdayNots")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Adaylar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Adaylars")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Mulakatlar", "Mulakatlar")
                        .WithMany("Adaylars")
                        .HasForeignKey("MulakatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Branslar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Branslar")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Duyurular", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Duyurulars")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.EPostaAdresleri", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("EPostaAdresleris")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Etkinlikler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Etkinliklers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Okullar", "Okullar")
                        .WithMany("Etkinliklers")
                        .HasForeignKey("OkulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Eyaletler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Eyaletlers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Ulkeler", "Ulkeler")
                        .WithMany("Eyaletlers")
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.FotoGaleri", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Adaylar", null)
                        .WithMany("FotoGaleri")
                        .HasForeignKey("AdaylarAdayId");

                    b.HasOne("YOGBIS.Data.DbModels.Duyurular", null)
                        .WithMany("FotoGaleri")
                        .HasForeignKey("DuyurularId");

                    b.HasOne("YOGBIS.Data.DbModels.Etkinlikler", null)
                        .WithMany("FotoGaleri")
                        .HasForeignKey("EtkinliklerEtkinlikId");

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("FotoGaleris")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Okullar", null)
                        .WithMany("FotoGaleri")
                        .HasForeignKey("OkullarOkulId");

                    b.HasOne("YOGBIS.Data.DbModels.Sehirler", null)
                        .WithMany("FotoGaleri")
                        .HasForeignKey("SehirlerSehirId");

                    b.HasOne("YOGBIS.Data.DbModels.Ulkeler", null)
                        .WithMany("FotoGaleri")
                        .HasForeignKey("UlkelerUlkeId");

                    b.HasOne("YOGBIS.Data.DbModels.Universiteler", null)
                        .WithMany("FotoGaleri")
                        .HasForeignKey("UniversitelerUniId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.GorevKararPdfGaleri", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.AdayGorevKaydi", "AdayGorevKaydi")
                        .WithMany("GorevKararPdfGaleri")
                        .HasForeignKey("AdayGorevKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("GorevKararPdfGaleris")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.IkametAdresleri", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Ilceler", "Ilceler")
                        .WithMany()
                        .HasForeignKey("IkametIlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("IkametAdresleris")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Ilceler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Iller", "Iller")
                        .WithMany()
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Ilcelers")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Iller", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Illers")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.IllerMdEPosta", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Iller", "Iller")
                        .WithMany("IllerMdEpostas")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("IllerMdEPostas")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Kitalar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.UlkeGruplari", null)
                        .WithMany("Kitalars")
                        .HasForeignKey("UlkeGruplariUlkeGrupId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Komisyonlar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Komisyonlars")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Mulakatlar", "Mulakatlar")
                        .WithMany("Komisyonlars")
                        .HasForeignKey("MulakatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.MulakatSorulari", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("MulakatSorularis")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Mulakatlar", "Mulakatlar")
                        .WithMany("MulakatSorularis")
                        .HasForeignKey("MulakatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Mulakatlar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.SoruDereceler", "Dereceler")
                        .WithMany()
                        .HasForeignKey("DereceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Mulakatlars")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Notlar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Notlars")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Ogrenciler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Ogrencilers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Siniflar", "Siniflar")
                        .WithMany("Ogrencilers")
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.OkulBilgi", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("OkulBilgis")
                        .HasForeignKey("KullaniciId");

                    b.HasOne("YOGBIS.Data.DbModels.Okullar", "Okullar")
                        .WithMany()
                        .HasForeignKey("OkulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Okullar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Okullars")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Sehirler", "Sehirler")
                        .WithMany("Okullars")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Personeller", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Personellers")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SSS", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("SSSs")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SSSCevap", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("SSSCevaps")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.SSS", "SSS")
                        .WithMany()
                        .HasForeignKey("SSSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Sehirler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Eyaletler", "Eyaletler")
                        .WithMany("Sehirlers")
                        .HasForeignKey("EyaletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Sehirlers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Ulkeler", null)
                        .WithMany("Sehirlers")
                        .HasForeignKey("UlkelerUlkeId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Siniflar", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Siniflars")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Subeler", "Subeler")
                        .WithMany("Siniflars")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruBankasi", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kaydeden")
                        .WithMany("SoruBankasis")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruBankasiLog", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kaydeden")
                        .WithMany("SoruBankasiLogs")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.SoruBankasi", "SoruBankasi")
                        .WithMany("SoruBankasiLogs")
                        .HasForeignKey("SoruBankasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruDerece", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.SoruDereceler", "SoruDereceler")
                        .WithMany("SoruDereces")
                        .HasForeignKey("DereceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.SoruBankasi", "SoruBankasi")
                        .WithMany("SoruDereces")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruDereceler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("SoruDerecelers")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruKategori", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.SoruKategoriler", "SoruKategoriler")
                        .WithMany("SoruKategoris")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YOGBIS.Data.DbModels.SoruBankasi", "SoruBankasi")
                        .WithMany("SoruKategoris")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruKategoriler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("SoruKategorilers")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.SoruOnay", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Onaylayan")
                        .WithMany("SoruOnays")
                        .HasForeignKey("OnaylayanId");

                    b.HasOne("YOGBIS.Data.DbModels.SoruBankasi", "SoruBankasi")
                        .WithMany("SoruOnays")
                        .HasForeignKey("SoruBankasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Subeler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Subelers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Okullar", "Okullar")
                        .WithMany("Subelers")
                        .HasForeignKey("OkulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Temsilcilikler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Temsilciliklers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Sehirler", "Sehirler")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.UlkeGruplari", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("UlkeGruplaris")
                        .HasForeignKey("KaydedenId");
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Ulkeler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Ulkelers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Kitalar", "Kitalar")
                        .WithMany("Ulkelers")
                        .HasForeignKey("KitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YOGBIS.Data.DbModels.Universiteler", b =>
                {
                    b.HasOne("YOGBIS.Data.DbModels.Kullanici", "Kullanici")
                        .WithMany("Universitelers")
                        .HasForeignKey("KaydedenId");

                    b.HasOne("YOGBIS.Data.DbModels.Sehirler", "Sehirler")
                        .WithMany("Universitelers")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
